ATTR_TYPE = 'type'
ATTR_NAME = 'name'
ATTR_DESCRIPTION = 'description'
ATTR_UNIT = 'unit'
ATTR_COERCE = 'coerce'
ATTR_CONSTRAINTS = 'constraints'
ATTR_LABEL = 'label'
ATTR_LABEL_SINGLE = 'single'
ATTR_LABEL_PLURAL = 'plural'
ATTR_LABEL_SYMBOL = 'symbol'
ATTR_MEASURES = 'measures'
ATTR_CONVERSION_TO_SI = 'conversion_to_si'
ATTR_FIELDS = 'fields'
ATTR_ATTRIBUTES = 'attributes'
ATTR_INPUT = 'input'
ATTR_OUTPUT = 'output'
ATTR_NEXT = 'next'

